drop user c##campEZ;
--계정생성
CREATE USER c##campEZ IDENTIFIED BY campEZ1234
    DEFAULT TABLESPACE users
    TEMPORARY TABLESPACE temp
    PROFILE DEFAULT;
--권한부여
GRANT CONNECT, RESOURCE TO c##campEZ;
GRANT CREATE VIEW, CREATE SYNONYM TO c##campEZ;
GRANT UNLIMITED TABLESPACE TO c##campEZ;
--락 풀기
ALTER USER c##campEZ ACCOUNT UNLOCK;